name: Print client payload
on:
  workflow_dispatch:
   
     
  repository_dispatch:
    types: [build]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "The version is ${{ github.event.client_payload.version }}"
      - name: Check out specific ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
  token:
   runs-on: ubuntu-latest
   steps:
    - name: Ejemplo usando el token
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           https://github.com{{ github.repository }}/issues
       
